### ISSUE TITLE
Plataform Windows

### ISSUE THREAD

**Issue by ghost** [Woopra/woopra-ios-sdk#7]
When I send an event from sdk, it works fine.... but in the dashboard, it shows Windows with unknown browser. Do you guys have any clue what can be happening?

Thanks

**Comment by philosoralphter** [comment]
I have been unable to reproduce this issues, and I definitely see recent events in your account right now that have "iOS" with version as visit properties.  Can you elaborate on what versions of iOS you think this is happening with? Or any steps you know of to reliably reproduce it?
